[package]
name = "kh-service-restart"
description = "KaptainhooK service restart tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kh-service-restart"
path = "src/main.rs"

[dependencies]
windows = { workspace = true }
