[package]
name = "kh-adapter-uninstall-state"
description = "KaptainhooK adapter: UninstallState restore"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kh-domain = { workspace = true }
windows = { workspace = true }
